import {DropdownButton, Dropdown} from 'react-bootstrap';
import React from 'react';

 
class DropDownAirports extends React.Component {
    render(){
        return(

    <DropdownButton
      alignRight
      title="Choose Source Airport"
      onSelect={this.props.airportChange}>
<Dropdown.Item eventKey="KABQ">Albuquerque International Sunport</Dropdown.Item>
 <Dropdown.Item eventKey="KADW">Joint Base Andrews</Dropdown.Item>
 <Dropdown.Item eventKey="KAFW">Fort Worth Alliance Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KAGS">Augusta Regional At Bush Field</Dropdown.Item>
 <Dropdown.Item eventKey="KAMA">Rick Husband Amarillo International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KATL">Hartsfield Jackson Atlanta International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KAUS">Austin Bergstrom International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KAVL">Asheville Regional Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KBAB">Beale Air Force Base</Dropdown.Item>
 <Dropdown.Item eventKey="KBAD">Barksdale Air Force Base</Dropdown.Item>
 <Dropdown.Item eventKey="KBDL">Bradley International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KBFI">Boeing Field King County International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KBGR">Bangor International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KBHM">Birmingham-Shuttlesworth International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KBIL">Billings Logan International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KBLV">Scott AFB/Midamerica Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KBMI">Central Illinois Regional Airport at Bloomington-Normal</Dropdown.Item>
 <Dropdown.Item eventKey="KBNA">Nashville International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KBOI">Boise Air Terminal/Gowen Field</Dropdown.Item>
 <Dropdown.Item eventKey="KBOS">General Edward Lawrence Logan International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KBUF">Buffalo Niagara International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KBWI">Baltimore/Washington International Thurgood Marshall Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KCAE">Columbia Metropolitan Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KCBM">Columbus Air Force Base</Dropdown.Item>
 <Dropdown.Item eventKey="KCHA">Lovell Field</Dropdown.Item>
 <Dropdown.Item eventKey="KCHS">Charleston Air Force Base-International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KCID">The Eastern Iowa Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KCLE">Cleveland Hopkins International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KCLT">Charlotte Douglas International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KCMH">John Glenn Columbus International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KCOS">City of Colorado Springs Municipal Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KCRP">Corpus Christi International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KCRW">Yeager Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KCVG">Cincinnati Northern Kentucky International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KCVS">Cannon Air Force Base</Dropdown.Item>
 <Dropdown.Item eventKey="KDAB">Daytona Beach International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KDAL">Dallas Love Field</Dropdown.Item>
 <Dropdown.Item eventKey="KDAY">James M Cox Dayton International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KDBQ">Dubuque Regional Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KDCA">Ronald Reagan Washington National Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KDEN">Denver International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KDFW">Dallas Fort Worth International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KDLF">DLF Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KDLH">Duluth International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KDOV">Dover Air Force Base</Dropdown.Item>
 <Dropdown.Item eventKey="KDSM">Des Moines International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KDTW">Detroit Metropolitan Wayne County Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KDYS">Dyess Air Force Base</Dropdown.Item>
 <Dropdown.Item eventKey="KEDW">Edwards Air Force Base</Dropdown.Item>
 <Dropdown.Item eventKey="KEND">Vance Air Force Base</Dropdown.Item>
 <Dropdown.Item eventKey="KERI">Erie International Tom Ridge Field</Dropdown.Item>
 <Dropdown.Item eventKey="KEWR">Newark Liberty International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KFFO">Wright-Patterson Air Force Base</Dropdown.Item>
 <Dropdown.Item eventKey="KFLL">Fort Lauderdale Hollywood International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KFSM">Fort Smith Regional Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KFTW">Fort Worth Meacham International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KFWA">Fort Wayne International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KGEG">Spokane International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KGPT">Gulfport Biloxi International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KGRB">Austin Straubel International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KGSB">Seymour Johnson Air Force Base</Dropdown.Item>
 <Dropdown.Item eventKey="KGSO">Piedmont Triad International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KGSP">Greenville Spartanburg International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KGUS">Grissom Air Reserve Base</Dropdown.Item>
 <Dropdown.Item eventKey="KHIB">Range Regional Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KHMN">Holloman Air Force Base</Dropdown.Item>
 <Dropdown.Item eventKey="KHOU">William P Hobby Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KHSV">Huntsville International Carl T Jones Field</Dropdown.Item>
 <Dropdown.Item eventKey="KHTS">Tri-State/Milton J. Ferguson Field</Dropdown.Item>
 <Dropdown.Item eventKey="KIAD">Washington Dulles International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KIAH">George Bush Intercontinental Houston Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KICT">Wichita Eisenhower National Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KIND">Indianapolis International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KJAN">Jackson-Medgar Wiley Evers International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KJAX">Jacksonville International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KJFK">John F Kennedy International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KJLN">Joplin Regional Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KLAS">McCarran International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KLAX">Los Angeles International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KLBB">Lubbock Preston Smith International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KLCK">Rickenbacker International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KLEX">Blue Grass Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KLFI">Langley Air Force Base</Dropdown.Item>
 <Dropdown.Item eventKey="KLFT">Lafayette Regional Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KLGA">La Guardia Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KLIT">Bill Hillary Clinton National Airport/Adams Field</Dropdown.Item>
 <Dropdown.Item eventKey="KLTS">Altus Air Force Base</Dropdown.Item>
 <Dropdown.Item eventKey="KLUF">Luke Air Force Base</Dropdown.Item>
 <Dropdown.Item eventKey="KMBS">MBS International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KMCF">Mac Dill Air Force Base</Dropdown.Item>
 <Dropdown.Item eventKey="KMCI">Kansas City International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KMCO">Orlando International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KMDW">Chicago Midway International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KMEM">Memphis International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KMGE">Dobbins Air Reserve Base</Dropdown.Item>
 <Dropdown.Item eventKey="KMGM">Montgomery Regional (Dannelly Field) Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KMHT">Manchester-Boston Regional Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KMIA">Miami International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KMKE">General Mitchell International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KMLI">Quad City International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KMLU">Monroe Regional Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KMOB">Mobile Regional Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KMSN">Dane County Regional Truax Field</Dropdown.Item>
 <Dropdown.Item eventKey="KMSP">Minneapolis-St Paul International/Wold-Chamberlain Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KMSY">Louis Armstrong New Orleans International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KMUO">Mountain Home Air Force Base</Dropdown.Item>
 <Dropdown.Item eventKey="KOAK">Metropolitan Oakland International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KOKC">Will Rogers World Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KOMA">Eppley Airfield</Dropdown.Item>
 <Dropdown.Item eventKey="KONT">Ontario International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KORD">Chicago O'Hare International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KORF">Norfolk International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KPAM">Tyndall Air Force Base</Dropdown.Item>
 <Dropdown.Item eventKey="KPBI">Palm Beach International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KPDX">Portland International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KPHF">Newport News Williamsburg International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KPHL">Philadelphia International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KPHX">Phoenix Sky Harbor International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KPIA">General Wayne A. Downing Peoria International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KPIT">Pittsburgh International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KPVD">Theodore Francis Green State Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KPWM">Portland International Jetport</Dropdown.Item>
 <Dropdown.Item eventKey="KRDU">Raleigh Durham International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KRFD">Chicago Rockford International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KRIC">Richmond International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KRND">Randolph Air Force Base</Dropdown.Item>
 <Dropdown.Item eventKey="KRNO">Reno Tahoe International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KROA">Roanokeâ Blacksburg Regional Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KROC">Greater Rochester International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KRST">Rochester International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KRSW">Southwest Florida International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KSAN">San Diego International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KSAT">San Antonio International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KSAV">Savannah Hilton Head International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KSBN">South Bend Regional Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KSDF">Louisville Muhammad Ali International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KSEA">Seattle Tacoma International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KSFB">Orlando Sanford International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KSFO">San Francisco International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KSGF">Springfield Branson National Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KSJC">Norman Y. Mineta San Jose International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KSKA">Fairchild Air Force Base</Dropdown.Item>
 <Dropdown.Item eventKey="KSLC">Salt Lake City International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KSMF">Sacramento International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KSNA">John Wayne Airport-Orange County Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KSPI">Abraham Lincoln Capital Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KSPS">Sheppard Air Force Base-Wichita Falls Municipal Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KSRQ">Sarasota Bradenton International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KSSC">Shaw Air Force Base</Dropdown.Item>
 <Dropdown.Item eventKey="KSTL">St Louis Lambert International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KSUS">Spirit of St Louis Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KSUU">Travis Air Force Base</Dropdown.Item>
 <Dropdown.Item eventKey="KSUX">Sioux Gateway Airport/Brigadier General Bud Day Field</Dropdown.Item>
 <Dropdown.Item eventKey="KSYR">Syracuse Hancock International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KSZL">Whiteman Air Force Base</Dropdown.Item>
 <Dropdown.Item eventKey="KTCM">McChord Air Force Base</Dropdown.Item>
 <Dropdown.Item eventKey="KTIK">Tinker Air Force Base</Dropdown.Item>
 <Dropdown.Item eventKey="KTLH">Tallahassee Regional Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KTOL">Toledo Express Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KTPA">Tampa International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KTRI">Tri-Cities Regional TN/VA Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KTUL">Tulsa International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KTUS">Tucson International Airport / Morris Air National Guard Base</Dropdown.Item>
 <Dropdown.Item eventKey="KTYS">McGhee Tyson Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KVBG">Vandenberg Air Force Base</Dropdown.Item>
 <Dropdown.Item eventKey="KVPS">Destin-Ft Walton Beach Airport</Dropdown.Item>
 <Dropdown.Item eventKey="KWRB">Robins Air Force Base</Dropdown.Item>
 <Dropdown.Item eventKey="PAFA">Fairbanks International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="PANC">Ted Stevens Anchorage International Airport</Dropdown.Item>
 <Dropdown.Item eventKey="PHNL">Daniel K Inouye International Airport</Dropdown.Item>
</DropdownButton>
)

}
}

export default DropDownAirports;
